import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 루트레이아웃(로그인 전후의 레이아웃이 다름.)
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
